name: Continuous

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Run tests
      run: cargo test --verbose
